import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../", import.meta.url);

test("MindMeal product metadata replaces starter content", async () => {
  const layout = await readFile(new URL("app/layout.tsx", root), "utf8");
  const page = await readFile(new URL("app/page.tsx", root), "utf8");
  assert.match(layout, /MindMeal 有意食/);
  assert.match(page, /訪客登入/);
  assert.match(page, /AI MEAL SCAN/);
  assert.doesNotMatch(layout, /codex-preview|Starter Project/);
});

test("core user flow screens are included", async () => {
  const page = await readFile(new URL("app/page.tsx", root), "utf8");
  for (const screen of ["onboarding", "album", "food-search", "manual-entry", "analysis", "result", "nearby", "store", "profile", "settings", "edit-meal"]) {
    assert.match(page, new RegExp(`\\b${screen}\\b`));
  }
});

test("v2 sitemap changes preserve the first-version body visual", async () => {
  const page = await readFile(new URL("app/page.tsx", root), "utf8");
  const yellowMan = await readFile(new URL("app/YellowManModel.tsx", root), "utf8");
  for (const label of ["首頁", "紀錄飲食", "下一餐地圖", "我的資料"]) {
    assert.match(page, new RegExp(label));
  }
  assert.match(page, /YellowManModel/);
  assert.match(yellowMan, /YELLOW_MAN\.glb/);
  assert.match(yellowMan, /FEMALE_MANNEQUIN\.glb/);
  assert.match(page, /function RingMetric/);
  assert.match(page, /熱 量 尚 缺/);
  assert.doesNotMatch(page, /className="gap-tabs"/);
  assert.match(page, /dashboard-swipe-card/);
  assert.match(page, /dashboard-data-window/);
  assert.match(page, /dashboard-fixed-figure/);
  assert.match(page, /活動紀錄/);
  assert.match(page, /消耗熱量/);
  assert.match(page, /體態趨勢／平衡分數/);
  assert.match(page, /今日紀錄餐點/);
  assert.match(page, /儲存這餐/);
  assert.match(page, /手動輸入/);
  assert.match(page, /Google Maps/);
  assert.doesNotMatch(page, /key: "trend"/);
  assert.doesNotMatch(page, /SCAN AREA/);
  assert.match(page, /function ProfileSettings/);
  assert.match(page, /editSetup=\{openSettings\}/);
  assert.match(page, /儲存所有設定/);
  assert.match(page, /尚未儲存變更/);
  assert.match(page, /<\/main><BottomNav screen="settings" go=\{leave\}/);
  assert.doesNotMatch(page, /<i>一次完成<\/i>/);
  assert.match(page, /麥當勞漢堡/);
  assert.match(page, /紅燒牛肉麵/);
  assert.match(page, /placeholder="搜尋：牛肉麵、漢堡、雞蛋…"/);
  assert.match(page, /function ManualEntry/);
  assert.match(page, /確認並查看分析/);
  assert.match(page, /className=\{`shutter-btn \$\{cameraState === "opening"/);
  assert.match(page, /選擇一張餐點照片？/);
  assert.match(page, /function AlbumGallery/);
  assert.match(page, /scrollIntoView\(\{ behavior: "smooth"/);
  assert.match(page, /editSetup\("contexts"\)/);
  assert.match(page, /id="settings-contexts"/);
  assert.match(page, /function calculateNutritionTargets/);
  assert.match(page, /Mifflin–St Jeor/);
  assert.match(page, /目前每日估算/);
  assert.match(page, /previewTargets\.calories/);
  assert.doesNotMatch(page, /<option>其他<\/option>/);
});

test("camera photos and food search use OpenRouter without exposing the key", async () => {
  const page = await readFile(new URL("app/page.tsx", root), "utf8");
  const styles = await readFile(new URL("app/globals.css", root), "utf8");
  const worker = await readFile(new URL("worker/meal-analysis.ts", root), "utf8");
  const workerEntry = await readFile(new URL("worker/ai-api.ts", root), "utf8");
  const searchWorker = await readFile(new URL("worker/food-search.ts", root), "utf8");
  const recommendationWorker = await readFile(new URL("worker/next-meal.ts", root), "utf8");
  const openRouter = await readFile(new URL("worker/openrouter.ts", root), "utf8");
  const workflow = await readFile(new URL(".github/workflows/pages.yml", root), "utf8");
  assert.match(page, /capture="environment"/);
  assert.match(page, /accept="image\/\*"/);
  assert.match(page, /navigator\.mediaDevices\.getUserMedia/);
  assert.match(page, /facingMode: \{ ideal: "environment" \}/);
  assert.match(page, /video: true/);
  assert.match(page, /允許並開啟相機/);
  assert.match(page, /相機權限/);
  assert.match(page, /blocked=\{scanning\}/);
  assert.match(page, /context\.drawImage\(video/);
  assert.match(page, /streamRef\.current\?\.getTracks\(\)\.forEach\(track => track\.stop\(\)\)/);
  assert.match(page, /void openCamera\(\)/);
  assert.match(page, /cameraState === "live" \? captureFrame\(\) : openCamera\(\)/);
  assert.match(styles, /\.camera-frame>video\{/);
  assert.doesNotMatch(page, /switchCamera|camera-switch|切換前後鏡頭/);
  assert.match(page, /VITE_MINDMEAL_ANALYSIS_API_URL/);
  assert.match(page, /analyzeMealPhoto/);
  assert.match(page, /正在分析餐點/);
  assert.match(page, /辨識餐點與食材/);
  assert.match(page, /判讀整份餐點/);
  assert.match(page, /整理營養資訊/);
  assert.match(page, /分析時間比平常久，請再稍候/);
  assert.match(page, /取消並重新選擇/);
  assert.match(page, /這張照片暫時無法辨識/);
  assert.match(page, /重新拍攝/);
  assert.match(page, /if \(!isActive\(\)\) return/);
  assert.match(page, /requestId\.current \+= 1/);
  assert.match(page, /setMeals\(current => \[\.\.\.current/);
  assert.match(page, /儲存這餐/);
  assert.match(workerEntry, /\/api\/analyze-meal/);
  assert.match(worker, /google\/gemini-3\.6-flash/);
  assert.match(searchWorker, /google\/gemini-2\.5-flash-lite/);
  assert.match(workerEntry, /\/api\/search-food/);
  assert.match(workerEntry, /\/api\/recommend-next-meal/);
  assert.match(recommendationWorker, /mindmeal_next_meal/);
  assert.match(recommendationWorker, /不可捏造店名、距離、價格或營業資訊/);
  assert.match(openRouter, /OPENROUTER_API_KEY/);
  assert.match(openRouter, /response_format/);
  assert.match(openRouter, /AI_USAGE/);
  assert.match(page, /searchFoodWithAi/);
  assert.match(page, /const \[submittedQuery, setSubmittedQuery\] = useState\(""/);
  assert.match(page, /\{submittedQuery \? <>/);
  assert.doesNotMatch(page, /autoSearchTimer/);
  assert.doesNotMatch(page, /const localMatches = foodLibrary\.filter/);
  assert.match(page, /food-search-loading/);
  assert.match(styles, /@keyframes food-search-progress/);
  assert.match(page, /X-MindMeal-Device/);
  assert.match(page, /AI 估算/);
  assert.doesNotMatch(page, />使用 AI 搜尋<\/button>/);
  assert.doesNotMatch(page, /OPENROUTER_API_KEY/);
  assert.match(styles, /\.scan-analysis-orbit\{/);
  assert.match(styles, /\.scan-failure\{/);
  assert.match(styles, /@media\(prefers-reduced-motion:reduce\)\{\.scan-analysis-orbit/);
  assert.match(workflow, /VITE_MINDMEAL_ANALYSIS_API_URL: https:\/\/mindmeal-nutrition-api\..+\/api\/analyze-meal/);
});

test("survey findings are reflected in the current experience", async () => {
  const page = await readFile(new URL("app/page.tsx", root), "utf8");
  assert.match(page, /NEXT MEAL NAVIGATION \/ 下一餐導航/);
  assert.match(page, /微調這餐/);
  assert.match(page, /飯量、醬料、食用量或食材/);
  assert.match(page, /1 碗約 200g/);
  assert.match(page, /下一餐怎麼選？/);
  assert.match(page, /recommendNextMealWithAi/);
  assert.match(page, /依今日紀錄整理/);
  assert.match(page, /店家與餐點資訊以地圖結果為準/);
});

test("login screen matches the minimal account and guest entry flow", async () => {
  const page = await readFile(new URL("app/page.tsx", root), "utf8");
  const styles = await readFile(new URL("app/globals.css", root), "utf8");
  const login = page.slice(page.indexOf("function Welcome"), page.indexOf("function ToggleChip"));
  assert.match(login, /type="email"/);
  assert.match(login, /name="password" type=\{loginPasswordVisible \? "text" : "password"\}/);
  assert.match(login, /name="new-password" type=\{signupPasswordVisible\.next \? "text" : "password"\}/);
  assert.match(login, /name="confirm-password" type=\{signupPasswordVisible\.confirm \? "text" : "password"\}/);
  assert.equal((login.match(/className="login-password-toggle"/g) || []).length, 3);
  assert.match(login, /顯示登入密碼/);
  assert.match(login, /隱藏登入密碼/);
  assert.match(login, /顯示設定密碼/);
  assert.match(login, /顯示確認密碼/);
  assert.match(login, /setSignupPasswordVisible\(\{ next: false, confirm: false \}\)/);
  assert.match(login, /建立帳號/);
  assert.match(login, /忘記密碼/);
  assert.match(login, /訪客登入/);
  assert.match(login, /onClick=\{\(\) => beginAuthFlow\("signup"\)\}>建立帳號<\/button><button type="button" onClick=\{\(\) => beginAuthFlow\("forgot"\)\}>忘記密碼<\/button><button type="button" onClick=\{guest\}>訪客登入/);
  assert.match(login, /className="login-orbit"/);
  assert.match(login, /帳號建立完成/);
  assert.match(login, /接著完成飲食資訊設定/);
  assert.match(login, /if \(authMode === "signup"\) setAccountCreated\(true\); else setPasswordReset\(true\)/);
  assert.match(login, /密碼重設完成/);
  assert.match(login, /請使用新密碼重新登入/);
  assert.match(login, /role="dialog" aria-modal="true"/);
  assert.match(login, /aria-hidden=\{completionOpen\} inert=\{completionOpen\}/);
  assert.match(login, /accountCreated \? "開始設定" : "返回登入"/);
  assert.match(login, /<Brand staticMark \/>/);
  assert.match(page, /get\("preview"\) === "login"/);
  assert.match(styles, /@keyframes login-orbit-dot/);
  assert.match(styles, /@keyframes login-orbit-float/);
  assert.match(styles, /\.login-screen>\.wave/);
  assert.match(login, /CREATE ACCOUNT \/ 01/);
  assert.match(login, /CREATE ACCOUNT \/ 02/);
  assert.match(login, /RESET PASSWORD \/ 01/);
  assert.match(login, /RESET PASSWORD \/ 02/);
  assert.match(login, /<h1>\{authMode === "signup" \? "建立帳號" : "重設密碼"\}<\/h1>/);
  assert.match(login, /先驗證你的信箱，我們會寄送六位數驗證碼。/);
  assert.match(login, /先驗證你的信箱，確認後即可設定新密碼。/);
  assert.match(login, /設定登入密碼/);
  assert.match(login, /重設登入密碼/);
  assert.match(login, /verificationCode\.length === 6/);
  assert.match(login, /newPassword\.length >= 6 && newPassword === confirmPassword/);
  assert.match(page, /guest=\{\(\) => \{ setProfile\(current => \(\{ \.\.\.current, email: "" \}\)\); setPendingAccountEmail\(""\); go\("onboarding"\); \}\}/);
  assert.match(styles, /\.login-flow-track\.stage-verify\{transform:translateX\(-33\.333333%\)\}/);
  assert.match(styles, /\.login-flow-track\.stage-password\{transform:translateX\(-66\.666667%\)\}/);
  assert.match(styles, /\.login-secondary-actions\{display:grid;justify-items:start;gap:0/);
  assert.match(styles, /\.login-form\{position:absolute;z-index:3;top:32%/);
  assert.match(styles, /\.auth-step-form\{position:absolute;z-index:3;top:32%/);
  assert.match(styles, /@media\(max-height:700px\)\{\.login-form,\.auth-step-form\{top:24%\}/);
  assert.match(page, /function isValidEmail/);
  assert.match(login, /信箱格式不正確，請重新確認/);
  assert.match(login, /id="login-email-error"/);
  assert.match(login, /id="signup-email-error"/);
  assert.match(page, /mindmeal-account-setup:/);
  assert.match(page, /setupComplete && profile\.name\.trim\(\)/);
  assert.match(page, /window\.localStorage\.setItem\(accountSetupKey\(pendingAccountEmail\), "complete"\)/);
  assert.match(styles, /\.login-field-error\{[^}]*color:#c83b32[^}]*font-weight:400/);
  assert.match(styles, /\.login-field\{position:relative/);
  assert.match(styles, /\.login-field-error\{position:absolute;right:3px;top:-1px[^}]*visibility:hidden/);
  assert.match(styles, /\.login-field-error\.is-visible\{visibility:visible\}/);
  assert.match(styles, /\.login-password-shell\{/);
  assert.match(styles, /\.login-password-toggle\{[^}]*width:44px[^}]*height:44px/);
  assert.match(login, /className=\{`login-field-error \$\{emailInvalid \? "is-visible" : ""\}`\}/);
  assert.doesNotMatch(login, /setEmailTouched\(true\)\} autoComplete/);
  assert.doesNotMatch(login, /setSignupEmailTouched\(true\)\} autoComplete/);
  assert.match(login, /onSubmit=\{event => \{ event\.preventDefault\(\); setEmailTouched\(true\);/);
  assert.match(login, /setSignupEmailTouched\(true\);/);
  assert.match(login, /setEmail\(event\.target\.value\); setEmailTouched\(false\);/);
  assert.match(login, /setSignupEmail\(event\.target\.value\); setSignupEmailTouched\(false\);/);
  const verifyPanel = login.slice(login.indexOf('<section className="auth-panel" aria-hidden={stage !== "verify"}>'), login.indexOf('<section className="auth-panel" aria-hidden={stage !== "password"}>'));
  assert.match(verifyPanel, /className="auth-send-code"/);
  assert.match(verifyPanel, /className="login-field auth-code-field"/);
  assert.match(verifyPanel, /disabled=\{!verificationSent\}/);
  assert.match(verifyPanel, />確認驗證 <span>→<\/span>/);
  assert.doesNotMatch(verifyPanel, /verificationSent && <label/);
  assert.equal((verifyPanel.match(/返回登入/g) || []).length, 1);
  assert.match(styles, /\.auth-send-code\{/);
  assert.match(styles, /\.account-created-backdrop\{/);
  assert.match(styles, /\.account-created-card\{/);
  assert.match(styles, /\.account-created-mark\{/);
});

test("onboarding and profile settings share the daily eating environment flow", async () => {
  const page = await readFile(new URL("app/page.tsx", root), "utf8");
  const onboardingStart = page.indexOf('<div className="step-body" key="taste">');
  const onboardingEnd = page.indexOf('<div className="step-body reminder-step"', onboardingStart);
  const onboarding = page.slice(onboardingStart, onboardingEnd);
  const settingsStart = page.indexOf('id="settings-contexts"');
  const settingsEnd = page.indexOf('<div className="settings-actions"', settingsStart);
  const settings = page.slice(settingsStart, settingsEnd);

  assert.ok(onboarding.indexOf('<label className="select-field">外食頻率') < onboarding.indexOf('<span className="field-title">日常飲食環境'));
  assert.match(onboarding, /\["自煮", "便利商店", "便當店", "餐廳"\]/);
  assert.match(onboarding, /可複選，將用於調整下一餐推薦。/);
  assert.match(page, /\? !profile\.activity/);
  assert.doesNotMatch(onboarding, /日常外食情境/);
  assert.ok(settings.indexOf("外食頻率") < settings.indexOf("常見選擇"));
  assert.match(settings, /<h2>日常飲食環境<\/h2>/);
  assert.match(page, /item === "便當" \? "便當店" : item/);
});

test("account profile separates identity editing from nutrition settings", async () => {
  const page = await readFile(new URL("app/page.tsx", root), "utf8");
  const styles = await readFile(new URL("app/globals.css", root), "utf8");
  const account = page.slice(page.indexOf("function AccountProfileScreen"), page.indexOf("function ProfileScreen"));
  const profile = page.slice(page.indexOf("function ProfileScreen"), page.indexOf("export default function HomePage"));
  const settings = page.slice(page.indexOf("function ProfileSettings"), page.indexOf("function ReminderSettingsScreen"));
  const dashboard = page.slice(page.indexOf("function Dashboard"), page.indexOf("function HistoryScreen"));

  assert.match(page, /\| "account" \|/);
  assert.match(account, /帳號與個人資料/);
  assert.match(account, /點擊頭像、名稱或信箱即可調整。/);
  assert.match(account, /name="profile-name"/);
  assert.match(account, /name="profile-email" type="email"/);
  assert.match(account, /<span>登入密碼<\/span><b>更改密碼 \{passwordEditorOpen \? "↑" : "↓"\}<\/b>/);
  assert.match(account, /aria-expanded=\{passwordEditorOpen\} aria-controls="account-password-panel"/);
  assert.match(account, /id="account-password-panel" className="account-password-panel"/);
  assert.doesNotMatch(account, /className="password-editor-backdrop"/);
  assert.match(account, /name="current-password" type=\{passwordVisible\.current \? "text" : "password"\}/);
  assert.match(account, /name="new-account-password" type=\{passwordVisible\.next \? "text" : "password"\}/);
  assert.match(account, /name="confirm-account-password" type=\{passwordVisible\.confirm \? "text" : "password"\}/);
  assert.match(account, /className="password-visibility-toggle"/);
  assert.match(account, /顯示目前密碼/);
  assert.match(account, /隱藏目前密碼/);
  assert.match(account, /togglePasswordVisibility\("next"\)/);
  assert.match(account, /togglePasswordVisibility\("confirm"\)/);
  assert.match(account, /setPasswordVisible\(\{ current: false, next: false, confirm: false \}\)/);
  assert.match(account, /passwordFields\.next\.length >= 6/);
  assert.match(account, /兩次輸入的密碼不同/);
  assert.match(account, /密碼已更新/);
  assert.doesNotMatch(account, /localStorage\.setItem\([^\n]*password/i);
  assert.match(account, /儲存個人資料/);
  assert.match(account, /const dirty = JSON\.stringify\(draft\) !== JSON\.stringify\(profile\)/);
  assert.match(account, /const leave = \(next: Screen\) => dirty \? setPendingScreen\(next\) : go\(next\)/);
  assert.match(account, /個人資料尚未儲存/);
  assert.match(account, /不儲存，直接離開/);
  assert.match(account, /aria-label=\{returnTo === "home" \? "返回首頁" : "返回我的資料"\}/);
  assert.match(account, /setAvatarEditor\(\{ src: avatar, x: 50, y: 50, zoom: 1\.3 \}\)/);
  assert.match(account, /className="avatar-editor-backdrop"/);
  assert.match(account, /role="dialog" aria-modal="true" aria-labelledby="avatar-editor-title"/);
  assert.match(account, /role="group" tabIndex=\{0\}/);
  assert.match(account, /type="range" min="1" max="2\.2"/);
  assert.match(account, /套用頭像/);
  assert.match(account, /avatarZoom: avatarEditor\.zoom/);
  assert.match(account, /blocked=\{editorOpen \|\| !!pendingScreen\}/);
  assert.doesNotMatch(settings, /className="settings-identity"/);
  assert.match(profile, /className="profile-hero profile-account-card"/);
  assert.match(profile, /帳號與個人資料/);
  assert.match(profile, /className="profile-account-action">查看/);
  assert.match(profile, /className="profile-logout-btn" onClick=\{\(\) => go\("welcome"\)\}>登出/);
  assert.match(profile, /setConfirmReset\(true\)/);
  assert.match(profile, /重設示範資料？/);
  assert.match(profile, /確認重設/);
  assert.match(profile, /role="switch" aria-checked=\{locationAllowed\}/);
  assert.match(profile, /className=\{`profile-location-switch/);
  assert.doesNotMatch(profile, /<b>\{profile\.location === "allowed" \? "已允許" : "手動地點"\}<\/b>/);
  assert.match(dashboard, /className="home-avatar" onClick=\{\(\) => go\("account"\)\} aria-label="開啟帳號與個人資料"/);
  assert.doesNotMatch(dashboard, /accountMenuOpen|account-menu-sheet|開啟帳號快捷選單/);
  assert.match(page, /if \(next === "account"\) setAccountReturnScreen\(screen === "home" \? "home" : "profile"\)/);
  assert.match(page, /returnTo=\{accountReturnScreen\}/);
  const resetFlow = page.slice(page.indexOf("const reset = () =>"), page.indexOf("if (!ready)", page.indexOf("const reset = () =>")));
  assert.match(resetFlow, /go\("onboarding"\)/);
  assert.doesNotMatch(resetFlow, /setScreen\("welcome"\)/);
  assert.match(page, /email: email\.trim\(\)/);
  assert.match(styles, /\.profile-account-card\{/);
  assert.match(styles, /\.account-profile-identity\{/);
  assert.match(styles, /\.home-avatar\{[^}]*width:44px[^}]*height:44px/);
  assert.match(styles, /\.home-avatar:focus-visible\{/);
  assert.match(styles, /\.profile-logout-btn\{/);
  assert.match(styles, /\.profile-location-switch\{/);
  assert.match(styles, /\.profile-location-switch\.is-on i\{background:var\(--orange\)/);
  assert.match(styles, /\.reset-confirm-modal \.delete-confirm\{/);
  assert.doesNotMatch(styles, /\.account-menu-sheet\{/);
  assert.match(styles, /\.account-profile-identity \.avatar-upload>span\{border:0/);
  assert.match(styles, /\.profile-account-card \.avatar\{border:0\}/);
  assert.match(styles, /\.avatar-editor-card\{/);
  assert.match(styles, /\.avatar-crop-stage\{[^}]*touch-action:none/);
  assert.match(styles, /\.account-password-panel\{/);
  assert.match(styles, /\.password-input-shell\{/);
  assert.match(styles, /\.password-visibility-toggle\{[^}]*width:44px[^}]*height:44px/);
  assert.doesNotMatch(styles, /\.password-editor-backdrop\{/);
  assert.match(styles, /\.account-update-toast\{/);
  assert.match(page, /if \(!raw\) window\.localStorage\.setItem\(avatarResetKey, "1"\)/);
});

test("next-meal view keeps the app shell and replaces the map with concise recommendations", async () => {
  const page = await readFile(new URL("app/page.tsx", root), "utf8");
  const styles = await readFile(new URL("app/globals.css", root), "utf8");
  const nextMeal = page.slice(page.indexOf("function NearbyRecommendations"), page.indexOf("function StoreDetail"));
  assert.match(nextMeal, /<AppHeader label="NEXT \/ MEAL" \/>/);
  assert.match(nextMeal, /<BottomNav screen="nearby" go=\{go\} blocked=\{showPermission\} \/>/);
  assert.match(nextMeal, /依今日紀錄整理/);
  assert.match(nextMeal, /推薦餐點/);
  assert.match(nextMeal, /在地圖搜尋/);
  assert.doesNotMatch(nextMeal, /查看更多餐點|收起其他餐點|more-meals/);
  assert.match(nextMeal, /plan\?\.recommendations\.map\(recommendation =>/);
  assert.match(nextMeal, /selectRecommendation\(recommendation\)/);
  assert.match(nextMeal, /navigator\.geolocation/);
  assert.match(nextMeal, /mindmeal-next-meal-cache-v1/);
  assert.doesNotMatch(nextMeal, /<iframe|real-map-card|MVP 示範/);
  assert.doesNotMatch(page, /const stores =/);
  assert.doesNotMatch(page, /好日子健康餐盒|SUBWAY|7-ELEVEN/);
  assert.match(styles, /\.nearby-screen>\.nearby-content\{transform:none!important/);
  assert.match(styles, /\.next-meal-card\{/);
  assert.match(styles, /@keyframes next-meal-progress/);
});

test("store detail adds actionable meal, ordering, nutrition, and diet guidance", async () => {
  const page = await readFile(new URL("app/page.tsx", root), "utf8");
  const styles = await readFile(new URL("app/globals.css", root), "utf8");
  const storeDetail = page.slice(page.indexOf("function StoreDetail"), page.indexOf("function EditMeal"));
  assert.match(storeDetail, /建議餐點/);
  assert.match(storeDetail, /建議點法/);
  assert.match(storeDetail, /營養估算/);
  assert.match(storeDetail, /飲食提醒/);
  assert.match(storeDetail, /recommendation\.orderTip/);
  assert.match(storeDetail, /recommendation\.calories/);
  assert.match(storeDetail, /recommendation\.notice/);
  assert.match(storeDetail, /Google Maps 搜尋附近店家/);
  assert.match(page, /const \[selectedRecommendation, setSelectedRecommendation\] = useState<NextMealRecommendation \| null>\(null\)/);
  assert.match(styles, /\.store-detail-content\{/);
});

test("meal records preserve timing metadata and history access", async () => {
  const page = await readFile(new URL("app/page.tsx", root), "utf8");
  assert.match(page, /type MealType = "早餐" \| "午餐" \| "晚餐" \| "宵夜／點心"/);
  assert.match(page, /function MealRecordFields/);
  assert.match(page, /aria-label="餐次與用餐時間"/);
  assert.equal(page.includes('<h2 id="meal-record-title">紀錄時間<\/h2>'), false);
  assert.match(page, /className="meal-time-trigger"/);
  assert.match(page, /aria-haspopup="dialog"/);
  assert.match(page, /className="meal-time-sheet"/);
  assert.match(page, /onEatenAtChange\(draftDate\.toISOString\(\)\)/);
  assert.match(page, /儲存補登紀錄/);
  assert.match(page, /function HistoryScreen/);
  assert.match(page, /查看全部飲食紀錄/);
  assert.match(page, /className="history-date-filter"/);
  assert.match(page, /className="history-date-trigger"/);
  assert.match(page, /className="history-calendar-sheet"/);
  assert.match(page, /sameLocalDate/);
});
test("meal-window reminders use three configurable ranges and skip recorded meals", async () => {
  const page = await readFile(new URL("app/page.tsx", root), "utf8");
  const styles = await readFile(new URL("app/globals.css", root), "utf8");
  const reminders = page.slice(page.indexOf("function ReminderSettingsScreen"), page.indexOf("function AccountProfileScreen"));
  assert.match(page, /type ReminderMeal = "早餐" | "午餐" | "晚餐"/);
  assert.match(page, /早餐: { enabled: true, start: "07:00", end: "10:00" }/);
  assert.match(page, /午餐: { enabled: true, start: "11:30", end: "14:00" }/);
  assert.match(page, /晚餐: { enabled: true, start: "17:30", end: "21:00" }/);
  assert.match(page, /function ReminderRows/);
  assert.match(page, /role="switch"/);
  assert.match(page, /deterministicMinute/);
  assert.match(page, /alreadyRecorded/);
  assert.match(page, /new Notification/);
  assert.equal(page.includes("setPendingMealType(mealType)"), true);
  assert.match(page, /現在補登，也能調整實際用餐時間/);
  assert.equal(page.includes("<option>用餐前 20 分鐘</option>"), false);
  assert.equal(page.includes(">點心</ToggleChip>"), false);
  assert.equal(styles.includes(".reminder-switch.is-on i{background:var(--orange)"), true);
  assert.equal(styles.includes(".reminder-divider{"), true);
  assert.match(reminders, /const dirty = JSON\.stringify\(draft\) !== JSON\.stringify\(profile\.reminderWindows\)/);
  assert.match(reminders, /提醒設定尚未儲存/);
  assert.match(reminders, /不儲存，直接離開/);
  assert.match(reminders, /inert=\{pendingLeave\}/);
});
test("meal analysis refinement keeps the edit affordance explicit and guards unsaved work", async () => {
  const page = await readFile(new URL("app/page.tsx", root), "utf8");
  const styles = await readFile(new URL("app/globals.css", root), "utf8");
  assert.match(page, /className="advanced-toggle"/);
  assert.equal(page.includes('className={`adjustment-state-icon ${advanced ? "is-expanded" : ""}`}'), true);
  assert.equal(page.includes('<path d="m6 15 6-6 6 6" />'), true);
  assert.equal(page.includes('確認微調並收起'), false);
  assert.equal(page.includes('strokeWidth="1.8"'), true);
  assert.equal(page.includes('<p className="analysis-adjustment-hint">飯量、醬料、食用量或食材</p>'), true);
  assert.equal(page.includes('<p className="estimate-note">AI 估算，儲存前請確認</p>'), true);
  assert.equal(page.includes('<strong>估算依據</strong>'), false);
  assert.equal(page.includes("aria-expanded={advanced}"), true);
  assert.match(page, /這餐尚未儲存/);
  assert.match(page, /不儲存，直接離開/);
  assert.match(page, /beforeunload/);
  assert.equal(page.includes('isTodayMeal ? "儲存這餐" : "儲存補登紀錄"'), true);
  assert.equal(page.includes("調整分析結果（份量、醬料、食材）"), false);
  assert.equal(styles.includes(".analysis-screen>.food-visual{height:240px}"), true);
  assert.equal(styles.includes(".analysis-content>.meal-record-fields"), true);
  assert.equal(styles.includes("padding:7px 42px 1px 0;"), true);
  assert.equal(styles.includes('.advanced-toggle[aria-expanded="true"]>span{'), true);
  assert.equal(styles.includes(".analysis-adjustment-card{padding:0!important}"), false);
});
test("saved meal result rotates calm daily nutrition totals without deficit language", async () => {
  const page = await readFile(new URL("app/page.tsx", root), "utf8");
  const styles = await readFile(new URL("app/globals.css", root), "utf8");
  const resultStart = page.indexOf("function Result");
  const resultEnd = page.indexOf("function NearbyRecommendations", resultStart);
  const result = page.slice(resultStart, resultEnd);
  assert.match(result, /meals: Meal\[\]/);
  assert.match(result, /sameLocalDate\(itemDate, resultDate\)/);
  assert.match(result, /result-nutrition-slide/);
  assert.match(result, /<h1>記錄完成<\/h1>/);
  assert.match(result, /result-metric-pager/);
  assert.match(result, /prefers-reduced-motion: reduce/);
  assert.match(result, /\}, 720\);\s*\}, 4200\);/);
  assert.match(result, /<section className=\{`result-nutrition-slide/);
  assert.doesNotMatch(result, /<section key=\{metric\.label\}/);
  assert.match(result, /<i key=\{metric\.label\} className="result-nutrition-ring"/);
  assert.match(styles, /\.result-nutrition-slide\{[^}]*transition:opacity \.7s ease-in-out/);
  assert.match(styles, /\.result-nutrition-slide\.is-hidden\{opacity:0\}/);
  assert.doesNotMatch(styles, /@keyframes result-slide-(?:enter|fade-in)/);
  assert.doesNotMatch(result, /className="success-mark"/);
  assert.doesNotMatch(result, /className="updated-progress"/);
  assert.doesNotMatch(result, /className="result-next"/);
  assert.doesNotMatch(result, /尚缺/);
  assert.equal(page.includes("<Result meal={meal} meals={meals} profile={profile} go={go} />"), true);
  assert.equal(styles.includes("Result page: calm rotating daily nutrition progress without deficit language."), true);
});
