"use client";

import { useEffect, useMemo, useState } from "react";

type Screen = "welcome" | "onboarding" | "home" | "scan" | "analysis" | "success" | "nearby" | "trend" | "profile";
type Profile = { age:string;height:string;weight:string;gender:string;activity:string;goal:string;preferences:string[];contexts:string[];location:boolean };
type Meal = { calories:number;protein:number;carbs:number;fat:number };

const emptyProfile:Profile={age:"28",height:"168",weight:"62",gender:"女性",activity:"每週 2–3 天",goal:"均衡飲食",preferences:["少辣"],contexts:["便利商店","便當"],location:false};
const targets={calories:1900,protein:120,carbs:220,fat:60,water:2000};
const base={calories:212,protein:0,carbs:34,fat:7,water:900};

function Brand(){return <div className="brand" aria-label="有意食 MindMeal"><span className="brand-line"/><span className="brand-zh">有 意 食</span><span className="brand-en">Mind Meal<span className="brand-dot">.</span></span></div>}
function Wave(){return <div className="wave" aria-hidden="true"/>}
function HumanFigure(){return <div className="human-wrap" aria-label="AI 身體需求：目前優先補充蛋白質"><div className="human" aria-hidden="true"><span className="head"/><span className="body"/><span className="arm arm-left"/><span className="arm arm-right"/><span className="leg leg-left"/><span className="leg leg-right"/></div><span className="human-shadow"/><span className="human-label">PROTEIN</span></div>}

function BottomNav({screen,go}:{screen:Screen;go:(s:Screen)=>void}){
 const items:{key:Screen;icon:string;label:string}[]=[{key:"home",icon:"⌂",label:"Home"},{key:"trend",icon:"↗",label:"Trend"},{key:"scan",icon:"+",label:"Scan"},{key:"nearby",icon:"⌖",label:"Nearby"},{key:"profile",icon:"○",label:"Me"}];
 return <nav className="bottom-nav" aria-label="主要導覽">{items.map(item=><button key={item.key} className={`nav-item ${screen===item.key?"active":""} ${item.key==="scan"?"scan-nav":""}`} onClick={()=>go(item.key)} aria-label={item.label} aria-current={screen===item.key?"page":undefined}><span className="nav-icon">{item.icon}</span><span className="nav-label">{item.label}</span></button>)}</nav>
}

function Welcome({start,demo}:{start:()=>void;demo:()=>void}){return <main className="welcome-screen screen-enter"><div className="welcome-top"><Brand/><span className="edition">MVP / 01</span></div><section className="welcome-copy"><span className="eyebrow">EAT WITH INTENTION.</span><h1>今天吃什麼，<br/>才能符合身體需求？</h1><p>不用計算每一口。拍下餐點，讓有意食告訴你下一餐的方向。</p></section><div className="welcome-orbit" aria-hidden="true"><span>有意</span><i/></div><div className="welcome-actions"><button className="primary-btn" onClick={start}>開始設定 <span>→</span></button><button className="text-btn" onClick={demo}>直接查看示範首頁</button></div><Wave/></main>}

function Onboarding({profile,setProfile,finish,back}:{profile:Profile;setProfile:(p:Profile)=>void;finish:()=>void;back:()=>void}){
 const [step,setStep]=useState(0); const update=(key:keyof Profile,value:string|boolean|string[])=>setProfile({...profile,[key]:value});
 const toggle=(key:"preferences"|"contexts",value:string)=>update(key,profile[key].includes(value)?profile[key].filter(v=>v!==value):[...profile[key],value]);
 const steps=[
  {kicker:"ABOUT YOU",title:"先認識一下你的身體",subtitle:"這些資料只用來建立本次示範建議。",body:<div className="form-grid"><label>年齡<input inputMode="numeric" value={profile.age} onChange={e=>update("age",e.target.value)}/><span>歲</span></label><label>身高<input inputMode="numeric" value={profile.height} onChange={e=>update("height",e.target.value)}/><span>cm</span></label><label>體重<input inputMode="numeric" value={profile.weight} onChange={e=>update("weight",e.target.value)}/><span>kg</span></label><div className="field-block"><span className="field-title">性別</span><div className="chip-row">{["女性","男性","其他"].map(v=><button className={profile.gender===v?"chip selected":"chip"} onClick={()=>update("gender",v)} key={v}>{v}</button>)}</div></div></div>},
  {kicker:"YOUR DIRECTION",title:"你想把飲食帶去哪裡？",subtitle:"不是限制，而是讓每一餐更靠近想要的狀態。",body:<><div className="choice-grid">{["減脂","維持","增肌","均衡飲食"].map(v=><button className={profile.goal===v?"choice-card selected":"choice-card"} onClick={()=>update("goal",v)} key={v}><span>{v==="減脂"?"↓":v==="增肌"?"↑":v==="維持"?"—":"◎"}</span>{v}</button>)}</div><div className="field-block"><span className="field-title">平常活動量</span><div className="chip-row wrap">{["幾乎不運動","每週 1 天","每週 2–3 天","每週 4 天以上"].map(v=><button className={profile.activity===v?"chip selected":"chip"} onClick={()=>update("activity",v)} key={v}>{v}</button>)}</div></div></>},
  {kicker:"YOUR TASTE",title:"保留你喜歡的吃法",subtitle:"可複選。AI 建議會避開不適合你的選項。",body:<div className="choice-grid preferences">{["素食","少辣","不吃牛","低糖","無乳製品","都可以"].map(v=><button className={profile.preferences.includes(v)?"choice-card selected":"choice-card"} onClick={()=>toggle("preferences",v)} key={v}>{v}<span>{profile.preferences.includes(v)?"✓":"+"}</span></button>)}</div>},
  {kicker:"REAL LIFE",title:"你最常在哪裡吃？",subtitle:profile.contexts.includes("便利商店")?"聽說便利商店每到月底的深夜，就會有超人出沒。":"選擇真實情境，建議才不會只是理想。",body:<><div className="choice-grid">{["便利商店","便當","餐廳","自煮"].map(v=><button className={profile.contexts.includes(v)?"choice-card selected":"choice-card"} onClick={()=>toggle("contexts",v)} key={v}>{v}<span>{profile.contexts.includes(v)?"✓":"+"}</span></button>)}</div><button className={`permission-card ${profile.location?"enabled":""}`} onClick={()=>update("location",!profile.location)}><span className="permission-icon">⌖</span><span><strong>附近餐飲建議</strong><small>選填，可隨時在設定中關閉</small></span><i>{profile.location?"ON":"稍後"}</i></button></>},
  {kicker:"READY",title:"你的今日方向已建立",subtitle:"以下為 MVP 示範估算，並非醫療或營養處方。",body:<div className="result-card"><span className="result-label">每日建議</span><strong>1,900</strong><small>kcal</small><div className="result-stats"><span><b>120g</b>蛋白質</span><span><b>2,000ml</b>水分</span><span><b>3+</b>蔬菜份數</span></div><p>今天先從第一餐開始，其他的交給我們慢慢整理。</p></div>}
 ];
 const invalid=step===0&&(!profile.age||!profile.height||!profile.weight);
 return <main className="onboarding-screen screen-enter"><header className="onboarding-header"><button onClick={step===0?back:()=>setStep(step-1)} aria-label="上一步">←</button><span>{step+1} / {steps.length}</span><Brand/></header><div className="step-track"><i style={{width:`${((step+1)/steps.length)*100}%`}}/></div><section className="onboarding-content" key={step}><span className="eyebrow">{steps[step].kicker}</span><h1>{steps[step].title}</h1><p>{steps[step].subtitle}</p><div className="step-body">{steps[step].body}</div></section><div className="sticky-action"><button disabled={invalid} className="primary-btn" onClick={step===steps.length-1?finish:()=>setStep(step+1)}>{step===steps.length-1?"開始第一天":"下一步"}<span>→</span></button></div></main>
}

function Progress({label,current,target,unit,accent=false}:{label:string;current:number;target:number;unit:string;accent?:boolean}){const pct=Math.min(100,Math.round(current/target*100));return <div className="progress-row"><div className="progress-head"><span>{label}</span><span><b>{current}</b> / {target}{unit}</span></div><div className="progress-track"><i className={accent?"accent":""} style={{width:`${pct}%`}}/></div></div>}

function Dashboard({meal,go}:{meal:Meal|null;go:(s:Screen)=>void}){
 const eaten=base.calories+(meal?.calories||0), remaining=Math.max(0,targets.calories-eaten), protein=meal?.protein||0, carbs=base.carbs+(meal?.carbs||0), fat=base.fat+(meal?.fat||0);
 return <main className="app-screen home-screen screen-enter"><header className="app-header"><Brand/><button className="streak" aria-label="連續紀錄七天"><b>7</b><span>DAYS</span></button></header><section className="hero"><span className="eyebrow">熱 量 尚 缺</span><div className="calorie-number">{remaining.toLocaleString()}<small>卡</small></div><p>{meal?"記錄完成。晚餐優先補充蛋白質與蔬菜。":"先記錄今天第一餐，讓方向更準確。"}</p></section><section className="nutrition-body-grid"><div className="nutrition-panel"><div className="panel-top"><span>TODAY / 01</span><span>估算</span></div><Progress label="蛋白質" current={protein} target={targets.protein} unit="g" accent/><Progress label="碳水" current={carbs} target={targets.carbs} unit="g"/><Progress label="脂肪" current={fat} target={targets.fat} unit="g"/><Progress label="水分" current={base.water} target={targets.water} unit="ml"/><div className="pager"><i/><i className="current"/><i/></div></div><HumanFigure/></section><section className="insight-strip"><span>AI DIRECTION</span><p>{meal?"蛋白質仍有缺口，下一餐選雞胸、豆腐、魚或茶葉蛋會更平衡。":"目前資料還很少。拍下餐點後，我們會把複雜數字整理成下一步。"}</p><button onClick={()=>go("nearby")}>看下一餐 →</button></section><button className="scan-card" onClick={()=>go("scan")}><span className="scan-label">SCAN AREA</span><span className="scan-window"><i/><b>＋</b><small>{meal?"記錄下一餐":"拍下第一餐"}</small></span><span className="scan-label">TAP TO START</span></button><section className="day-summary"><div><span className="eyebrow">TODAY&apos;S BALANCE</span><strong>{meal?"76":"—"}</strong><small>{meal?"GOOD START":"WAITING"}</small></div><ul><li className={meal?"done":""}><span>早餐</span><b>{meal?"已記錄":"尚未記錄"}</b></li><li><span>午餐</span><b>下一餐</b></li><li><span>晚餐</span><b>等待中</b></li></ul></section><BottomNav screen="home" go={go}/></main>
}

function Scan({go}:{go:(s:Screen)=>void}){const[scanning,setScanning]=useState(false);const begin=()=>{setScanning(true);window.setTimeout(()=>go("analysis"),1500)};return <main className="app-screen dark-screen scan-screen screen-enter"><header className="dark-header"><button onClick={()=>go("home")}>←</button><Brand/><span>DEMO</span></header><section className="scan-copy"><span className="eyebrow">AI MEAL SCAN</span><h1>{scanning?"正在整理這一餐":"讓食物進入框內"}</h1><p>{scanning?"辨識主要食材與份量，請稍候。":"原型會使用示範餐點，不會上傳照片。"}</p></section><button className={`camera-frame ${scanning?"scanning":""}`} onClick={begin} disabled={scanning}><span className="corner c1"/><span className="corner c2"/><span className="corner c3"/><span className="corner c4"/><i className="scan-line"/><b>{scanning?"ANALYZING...":"+"}</b></button><div className="capture-options"><button onClick={begin}>拍照</button><button onClick={begin}>相簿</button><button onClick={begin}>搜尋</button><button onClick={begin}>常吃</button></div><BottomNav screen="scan" go={go}/></main>}

function Option({title,values,value,setValue}:{title:string;values:string[];value:string;setValue:(v:string)=>void}){return <div className="option-block"><span>{title}</span><div>{values.map(v=><button key={v} className={value===v?"selected":""} onClick={()=>setValue(v)}>{v}</button>)}</div></div>}
function Analysis({save,go}:{save:(m:Meal)=>void;go:(s:Screen)=>void}){
 const[rice,setRice]=useState("一碗"),[sauce,setSauce]=useState("正常"),[finished,setFinished]=useState("吃完");
 const meal=useMemo(()=>{const m=rice==="半碗"?.78:rice==="加飯"?1.18:1,e=sauce==="多"?55:sauce==="少"?-25:0,f=finished==="剩一些"?.8:1;return{calories:Math.round((620*m+e)*f),protein:Math.round(42*f),carbs:Math.round(72*m*f),fat:Math.round((18+e*.08)*f)}},[rice,sauce,finished]);
 return <main className="app-screen analysis-screen screen-enter"><header className="simple-header"><button onClick={()=>go("scan")}>←</button><span>AI 分析結果</span><i>估算</i></header><section className="food-visual"><div className="plate"><span className="food rice"/><span className="food chicken"/><span className="food greens g1"/><span className="food greens g2"/></div><span className="detected">辨識完成 · 4 項食材</span></section><section className="analysis-content"><span className="eyebrow">CHICKEN RICE BOWL</span><h1>香煎雞胸時蔬飯</h1><div className="macro-summary"><span><b>{meal.calories}</b> kcal</span><span><b>{meal.protein}g</b> 蛋白質</span><span><b>{meal.carbs}g</b> 碳水</span><span><b>{meal.fat}g</b> 脂肪</span></div><div className="detected-foods"><span>雞胸肉</span><span>白飯</span><span>花椰菜</span><span>玉米筍</span></div><Option title="飯量" values={["半碗","一碗","加飯"]} value={rice} setValue={setRice}/><Option title="醬料" values={["少","正常","多"]} value={sauce} setValue={setSauce}/><Option title="實際吃完" values={["吃完","剩一些"]} value={finished} setValue={setFinished}/><p className="estimate-note">此為 MVP 示範估算，實際營養會因食材與烹調方式不同。</p><button className="primary-btn" onClick={()=>save(meal)}>儲存這餐 <span>→</span></button></section></main>
}

function Success({meal,go}:{meal:Meal;go:(s:Screen)=>void}){return <main className="success-screen screen-enter"><Brand/><div className="success-mark">✓</div><span className="eyebrow">MEAL SAVED</span><h1>第一餐，完成。</h1><p>已加入 <b>{meal.calories} kcal</b>。今天油脂已經較充足，下一餐用清爽蛋白質與蔬菜接住就好。</p><div className="success-actions"><button className="primary-btn" onClick={()=>go("home")}>回到今天 <span>→</span></button><button className="secondary-btn" onClick={()=>go("nearby")}>找附近吃什麼</button></div><Wave/></main>}

const stores=[{name:"好日子健康餐盒",distance:"350m",fit:"雞胸＋雙份蔬菜",score:"96"},{name:"SUBWAY",distance:"480m",fit:"嫩切雞肉沙拉",score:"92"},{name:"7-ELEVEN",distance:"120m",fit:"茶葉蛋＋無糖豆漿",score:"88"}];
function Nearby({go}:{go:(s:Screen)=>void}){const[checked,setChecked]=useState<string[]>([]);const shopping=["舒肥雞胸","茶葉蛋 × 2","無糖豆漿","生菜沙拉"];return <main className="app-screen nearby-screen screen-enter"><header className="app-header"><Brand/><span className="edition">NEXT / MEAL</span></header><section className="nearby-hero"><span className="eyebrow">NEXT MEAL DIRECTION</span><h1>蛋白質還差<br/><b>約 78g</b></h1><p>最後一餐不用完美，只要優先選一份蛋白質，再加蔬菜就很好。</p></section><section className="map-card" aria-label="附近店家示意地圖"><div className="map-grid"/><span className="road r1"/><span className="road r2"/><i className="pin p1">1</i><i className="pin p2">2</i><i className="pin p3">3</i><div className="you-are-here">YOU<br/>ARE HERE</div><small>示意地圖 · 未使用即時定位</small></section><section className="store-list"><div className="section-heading"><span>附近推薦</span><small>依今日缺口排序</small></div>{stores.map((store,i)=><article className="store-card" key={store.name}><span className="store-rank">0{i+1}</span><div><h2>{store.name}</h2><p>{store.fit}</p><small>{store.distance} · 示範店家</small></div><strong>{store.score}</strong></article>)}</section><section className="shopping-list"><div className="section-heading"><span>順手採買</span><small>{checked.length} / {shopping.length}</small></div>{shopping.map(item=><button key={item} className={checked.includes(item)?"checked":""} onClick={()=>setChecked(checked.includes(item)?checked.filter(x=>x!==item):[...checked,item])}><i>{checked.includes(item)?"✓":""}</i><span>{item}</span><b>＋</b></button>)}</section><BottomNav screen="nearby" go={go}/></main>}

function Trend({go}:{go:(s:Screen)=>void}){return <main className="app-screen trend-screen screen-enter"><header className="app-header"><Brand/><span className="edition">7 DAYS</span></header><section className="page-title"><span className="eyebrow">YOUR RHYTHM</span><h1>不追求完美，<br/>只看正在形成的節奏。</h1></section><section className="trend-grid"><article className="trend-card dark"><span>平衡分數</span><strong>76</strong><small>本週平均 +4</small><div className="mini-bars">{[48,62,55,70,66,82,76].map((v,i)=><i key={i} style={{height:`${v}%`}}/>)}</div></article><article className="trend-card acid"><span>蛋白質</span><strong>72%</strong><small>目標達成率</small><div className="ring-stat"/></article><article className="trend-card wide"><span>飲水</span><strong>1.7L</strong><small>日平均</small><div className="water-line"><i/><i/><i/><i/><i/><i/><i/></div></article><article className="trend-card"><span>體重</span><strong>61.8</strong><small>kg · 平穩</small></article><article className="trend-card"><span>已記錄</span><strong>12</strong><small>餐 / 本週</small></article></section><BottomNav screen="trend" go={go}/></main>}

function ProfileScreen({profile,go,reset}:{profile:Profile;go:(s:Screen)=>void;reset:()=>void}){return <main className="app-screen profile-screen screen-enter"><header className="app-header"><Brand/><span className="edition">ME / 01</span></header><section className="profile-hero"><span className="avatar">意</span><div><span className="eyebrow">YOUR DIRECTION</span><h1>{profile.goal}</h1><p>{profile.activity}</p></div></section><section className="profile-list"><article><span>每日目標</span><b>1,900 kcal</b></article><article><span>飲食偏好</span><b>{profile.preferences.join("、")||"無"}</b></article><article><span>外食情境</span><b>{profile.contexts.join("、")||"未設定"}</b></article><article><span>附近餐飲建議</span><b>{profile.location?"已開啟":"未開啟"}</b></article><article><span>通知</span><b>晚餐前提醒</b></article></section><button className="reset-btn" onClick={reset}>重設示範資料</button><p className="prototype-note">MindMeal MVP · 所有健康數值皆為互動示範</p><BottomNav screen="profile" go={go}/></main>}

export default function HomePage(){
 const[screen,setScreen]=useState<Screen>("welcome"),[profile,setProfile]=useState<Profile>(emptyProfile),[meal,setMeal]=useState<Meal|null>(null),[ready,setReady]=useState(false);
 useEffect(()=>{const restore=window.setTimeout(()=>{try{const data=window.localStorage.getItem("mindmeal-demo");if(data){const p=JSON.parse(data);setProfile(p.profile||emptyProfile);setMeal(p.meal||null);setScreen(p.onboarded?"home":"welcome")}}catch{/* use demo defaults */}setReady(true)},0);return()=>window.clearTimeout(restore)},[]);
 useEffect(()=>{if(ready)window.localStorage.setItem("mindmeal-demo",JSON.stringify({profile,meal,onboarded:screen!=="welcome"&&screen!=="onboarding"}))},[profile,meal,screen,ready]);
 const go=(next:Screen)=>{setScreen(next);window.scrollTo({top:0,behavior:"smooth"})}; const reset=()=>{window.localStorage.removeItem("mindmeal-demo");setProfile(emptyProfile);setMeal(null);setScreen("welcome")};
 if(!ready)return <main className="loading-screen"><Brand/><span>LOADING DIRECTION</span></main>;
 if(screen==="welcome")return <Welcome start={()=>go("onboarding")} demo={()=>{setMeal({calories:620,protein:42,carbs:72,fat:18});go("home")}}/>;
 if(screen==="onboarding")return <Onboarding profile={profile} setProfile={setProfile} finish={()=>go("home")} back={()=>go("welcome")}/>;
 if(screen==="scan")return <Scan go={go}/>; if(screen==="analysis")return <Analysis go={go} save={m=>{setMeal(m);go("success")}}/>; if(screen==="success"&&meal)return <Success meal={meal} go={go}/>; if(screen==="nearby")return <Nearby go={go}/>; if(screen==="trend")return <Trend go={go}/>; if(screen==="profile")return <ProfileScreen profile={profile} go={go} reset={reset}/>; return <Dashboard meal={meal} go={go}/>;
}
